-- MySQL Script generated by MySQL Workbench
-- Wed Jan  8 18:37:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`variacoes_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`variacoes_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(245) NULL,
  `qtd_disponivel` INT NULL,
  `nome_variacao` VARCHAR(245) NULL,
  `preco` FLOAT NULL,
  `preco_de` FLOAT NULL,
  `peso` INT NULL,
  `ordem` INT NULL,
  `produto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_variacao_produto_produtos_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_variacao_produto_produtos`
    FOREIGN KEY (`produto_id`)
    REFERENCES `shop`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`imagens_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`imagens_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(245) NULL,
  `url` VARCHAR(245) NULL,
  `ordem` INT NULL,
  `variacao_produto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagens_produto_variacoes_produto1_idx` (`variacao_produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_imagens_produto_variacoes_produto1`
    FOREIGN KEY (`variacao_produto_id`)
    REFERENCES `shop`.`variacoes_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(245) NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`categorias_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`categorias_produtos` (
  `produto_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`produto_id`, `categoria_id`),
  INDEX `fk_produtos_has_categorias_categorias1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_produtos_has_categorias_produtos1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_has_categorias_produtos1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `shop`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_categorias_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `shop`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`tipos_banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`tipos_banner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_banner` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`banners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(245) NULL,
  `tipo_banner_id` INT NOT NULL,
  `url` VARCHAR(245) NULL,
  `ordem` INT NULL,
  `image_url` VARCHAR(245) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_banners_tipos_banner1_idx` (`tipo_banner_id` ASC) VISIBLE,
  CONSTRAINT `fk_banners_tipos_banner1`
    FOREIGN KEY (`tipo_banner_id`)
    REFERENCES `shop`.`tipos_banner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
